version: '3'
services:
  api:
    image: penguinjudge/backend
    build: backend/
    ports:
      - 5000:5000
      - 8000:5000
    volumes:
      - ./.docker-compose:/mnt:ro
    command: /bin/sh -c "python /mnt/prepare.py && penguin_judge api -c /mnt/config.ini"
    depends_on:
      - mq
      - db
  worker:
    image: penguinjudge/backend
    build: backend/
    volumes:
      - ./.docker-compose:/mnt:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "python /mnt/prepare.py && penguin_judge worker -c /mnt/config.ini"
    depends_on:
      - mq
      - db
      - puller
  gui:
    image: penguinjudge/frontend
    build: frontend
    depends_on:
      - api
    ports:
      - 8080:80
  mq:
    image: rabbitmq:alpine
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
  puller:
    image: docker
    volumes:
      - ./container:/mnt:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "/mnt/pull.sh && while true; do sleep 86400; done"
