name: Backend CI

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'backend/**'

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
      mq:
        image: rabbitmq:alpine
        ports:
          - 5672:5672
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install/Upgrade pip/dependencies
      run: |
        cd ./backend
        pip install -U pip setuptools
        pip install .[develop]
    - name: Lint with flake8
      run: |
        cd ./backend
        flake8 penguin_judge tests
    - name: Check typehints
      run: |
        cd ./backend
        mypy -p penguin_judge
    - name: Prepare test environments
      run: |
        cd .docker-compose
        sed -i -e 's/db:/localhost:/' config.ini
        sed -i -e 's/mq:/localhost:/' config.ini
        python ./prepare.py
    - name: Execute small tests
      run: |
        export PENGUIN_JUDGE_TEST_DB_URL=`grep sql .docker-compose/config.ini | cut -d ' ' -f 3`
        cd ./backend
        nose2 -v tests
