name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install/Upgrade pip/pipenv/dependencies
      run: |
        cd ./backend
        python -m pip install -U pip setuptools pipenv
        pipenv install --system
        pipenv install --system -d
    - name: Lint with flake8
      run: |
        cd ./backend && flake8 penguin_judge
    - name: Check typehints
      run: |
        cd ./backend && mypy -p penguin_judge
