name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pip and pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install penguin_judge backend
      run: |
        pip install ./backend/
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 ./backend/
