name: Python package

on: [push]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
      mq:
        image: rabbitmq:alpine
        ports:
          - 5672:5672
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install/Upgrade pip/dependencies
      run: |
        cd ./backend
        pip install -U pip setuptools
        pip install .[develop]
    - name: Lint with flake8
      run: |
        cd ./backend
        flake8 penguin_judge tests
    - name: Check typehints
      run: |
        cd ./backend
        mypy -p penguin_judge
    - name: Prepare test environments
      run: |
        cd .docker-compose
        sed -i -e 's/db:/localhost:/' config.ini
        sed -i -e 's/mq:/localhost:/' config.ini
        python ./prepare.py
    - name: Execute small tests
      run: |
        export PENGUIN_JUDGE_TEST_DB_URL=`grep sql .docker-compose/config.ini | cut -d ' ' -f 3`
        cd ./backend
        nose2 -v tests
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: |
        cd ./frontend
        npm ci
    - name: Build test
      run: |
        cd ./frontend
        webpack -p
  docker-image-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build backend docker image
      run: |
        component="backend"
        ref_short=$(basename ${{ github.ref }})
        echo component "$component"
        echo ref_short "$ref_short"
        # build
        cd ./$component
        docker build -t "$component:latest" .
        # tag and push SHA1
        docker tag "$component:latest" "penguinjudge/$component:${{ github.sha }}"
        docker push "penguinjudge/$component:${{ github.sha }}"
        # tag and push ref name
        docker tag "$component:latest" "penguinjudge/$component:$ref_short"
        docker push "penguinjudge/$component:$ref_short"
        # tag and push latest if this action is running on master
        if [ "$ref_short" = "master" ]; then
          docker push "penguinjudge/$component:latest"
        fi
  docker-image-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build frontend docker image
      run: |
        component="frontend"
        ref_short=$(basename ${{ github.ref }})
        echo component "$component"
        echo ref_short "$ref_short"
        # build
        cd ./$component
        docker build -t "$component:latest" .
        # tag and push SHA1
        docker tag "$component:latest" "penguinjudge/$component:${{ github.sha }}"
        docker push "penguinjudge/$component:${{ github.sha }}"
        # tag and push ref name
        docker tag "$component:latest" "penguinjudge/$component:$ref_short"
        docker push "penguinjudge/$component:$ref_short"
        # tag and push latest if this action is running on master
        if [ "$ref_short" = "master" ]; then
          docker push "penguinjudge/$component:latest"
        fi
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          cd ./agent
          cargo build --verbose
      - name: Run tests
        run: |
          cd ./agent
          RUST_BACKTRACE=1 cargo test --verbose
